---
apiVersion: v1
kind: Service
metadata:
  name: product-catalogue
  labels:
    name: product-catalogue
spec:
  selector:
    app: product-catalogue
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.
  
  
#  type: LoadBalancer
 # ports:
  #  - port: 80
   #   targetPort: 8080
