---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalogue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalogue
  template:
    metadata:
      labels:
        app: product-catalogue
    spec:
      imagePullSecrets:
        - name: my-docker-container-registry
      containers:
        - name: product-catalogue
          image: ayush0773/product-catalogue:product-catalogue
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: product-catalogue
  labels:
    name: product-catalogue
spec:
  selector:
    app: product-catalogue
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080

